server:
  port: ${AUTH_SERVICE_PORT:8081}

spring:
  application:
    name: auth-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  rsa:
    issuer: auth-service
    key-id: my-key-1
    access-token-expiration: 3600000  # 1 hour
    private-key-file: classpath:keys/private.pem
    public-key-file: classpath:keys/public.pem
