server:
  port: ${AUTH_SERVICE_PORT:8081}

spring:
  application:
    name: auth-service

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  rsa:
    issuer: auth-service
    key-id: my-key-1
    access-token-expiration: 3600000  # 1 hour
    private-key-file: classpath:keys/private.pem
    public-key-file: classpath:keys/public.pem

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:localhost}  # optional for local dev
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}:${spring.profiles.active}
