server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:localhost}  # local dev
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}:${spring.profiles.active}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,loggers   # dev monitoring

  endpoint:
    health:
      show-details: always

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

swagger:
  server-url: http://localhost:${server.port}