package com.smartcart.common.event;

public enum EventType {

    USER_CREATED,
    USER_UPDATED,

    ORDER_CREATED,
    ORDER_CANCELLED,

    PAYMENT_INITIATED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,

    INVENTORY_RESERVED,
    INVENTORY_RELEASED,
    INVENTORY_RESERVATION_FAILED
}
