version: "3.9"

networks:
  smartcart-network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
  kafka_data:
  grafana_data:

services:

  # ---------------------------
  # DATABASES
  # ---------------------------

  postgres:
    image: postgres:16-alpine
    container_name: smartcart-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - smartcart-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  mongodb:
    image: mongo:7
    container_name: smartcart-mongodb
    restart: unless-stopped
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongo_data:/data/db
    networks:
      - smartcart-network

  redis:
    image: redis:7-alpine
    container_name: smartcart-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - smartcart-network

  # ---------------------------
  # KAFKA (KRaft mode - modern)
  # ---------------------------

  kafka:
    image: apache/kafka:3.7.0
    container_name: smartcart-kafka
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:${KAFKA_PORT},CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:${KAFKA_PORT}
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    volumes:
      - kafka_data:/tmp/kraft-combined-logs
    networks:
      - smartcart-network


  # ---------------------------
  # DISCOVERY
  # ---------------------------

  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    restart: unless-stopped
    ports:
      - "${EUREKA_PORT}:${EUREKA_PORT}"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - postgres
    networks:
      - smartcart-network

  # ---------------------------
  # API GATEWAY
  # ---------------------------

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:${EUREKA_PORT}/eureka/
    depends_on:
      - discovery-server
    networks:
      - smartcart-network

  # ---------------------------
  # BUSINESS SERVICES
  # ---------------------------

  auth-service:
    build: ./auth-service
    container_name: auth-service
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:${EUREKA_PORT}/eureka/
    depends_on:
      - discovery-server
    networks:
      - smartcart-network

  user-service:
    build: ./user-service
    container_name: user-service
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:${POSTGRES_PORT}/${USER_DB}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:${EUREKA_PORT}/eureka/
    depends_on:
      - postgres
      - discovery-server
    networks:
      - smartcart-network

  product-service:
    build: ./product-service
    container_name: product-service
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:${MONGO_PORT}/${PRODUCT_DB}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:${EUREKA_PORT}/eureka/
    depends_on:
      - mongodb
      - discovery-server
    networks:
      - smartcart-network

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:${POSTGRES_PORT}/${INVENTORY_DB}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:${EUREKA_PORT}/eureka/
    depends_on:
      - postgres
      - discovery-server
    networks:
      - smartcart-network

  order-service:
    build: ./order-service
    container_name: order-service
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:${POSTGRES_PORT}/${ORDER_DB}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:${EUREKA_PORT}/eureka/
    depends_on:
      - postgres
      - kafka
      - discovery-server
    networks:
      - smartcart-network

  payment-service:
    build: ./payment-service
    container_name: payment-service
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:${POSTGRES_PORT}/${PAYMENT_DB}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:${EUREKA_PORT}/eureka/
    depends_on:
      - postgres
      - kafka
      - discovery-server
    networks:
      - smartcart-network

  notification-service:
    build: ./notification-service
    container_name: notification-service
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:${MONGO_PORT}/${NOTIFICATION_DB}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:${EUREKA_PORT}/eureka/
    depends_on:
      - mongodb
      - kafka
      - discovery-server
    networks:
      - smartcart-network

  # ---------------------------
  # MONITORING
  # ---------------------------

  prometheus:
    image: prom/prometheus:v2.48.1
    container_name: smartcart-prometheus
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - smartcart-network

  grafana:
    image: grafana/grafana:10.2.2
    container_name: smartcart-grafana
    ports:
      - "${GRAFANA_PORT}:${GRAFANA_PORT}"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - smartcart-network
