server:
  port: ${PAYMENT_SERVICE_PORT:8086}

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/payment_db   # Docker container for prod
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate    # prod: validate schema only
    show-sql: false         # prod: disable SQL logging

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:8081/.well-known/jwks.json

  kafka:
    bootstrap-servers: kafka:${KAFKA_PORT}   # prod Kafka
    consumer:
      group-id: payment-service
      auto-offset-reset: earliest

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:${EUREKA_PORT:8761}/eureka/
    fetch-registry: true
    register-with-eureka: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:payment-service}
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}:${spring.profiles.active}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus               # expose all actuator endpoints for monitoring

  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: when-authorized  # only admins see full health info

  metrics:
    export:
      prometheus:
        enabled: true                # allow Prometheus scraping
    enable:
      all: true                      # enable all default metrics

  tracing:
    sampling:
      probability: 0.1                # trace 10% of requests to reduce overhead

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logging:
  level:
    root: WARN
    org.springframework: WARN
    com.smartcart.payment: INFO

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

swagger:
  server-url: https://api.smartcart.com
