spring:
  application:
    name: user-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

eureka:
  instance:
    metadata-map:
      version: 1.0
      environment: ${spring.profiles.active}

management:
  endpoints:
    web:
      base-path: /actuator

swagger:
  title: User Service API
  description: APIs for managing users in SmartCart
  version: v1.0