server:
  port: ${ORDER_SERVICE_PORT:8085}

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://postgres:5432/order_db  # Docker service name
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate   # prod: validate schema only
    show-sql: false        # prod: don’t show SQL

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:8081/.well-known/jwks.json

  kafka:
    bootstrap-servers: kafka:${KAFKA_PORT}  # production Kafka bootstrap server

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:${EUREKA_PORT}/eureka/
    fetch-registry: true
    register-with-eureka: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:order-service}
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}:${spring.profiles.active}

management:
  endpoints:
    web:
      exposure:
        include: "*"                 # expose all actuator endpoints for monitoring
      base-path: /actuator
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: when-authorized  # only admins see full health info
  metrics:
    export:
      prometheus:
        enabled: true                # allow Prometheus scraping
    enable:
      all: true                      # enable all default metrics
  tracing:
    sampling:
      probability: 0.1                # trace 10% of requests to reduce overhead

logging:
  level:
    root: WARN
    org.springframework: WARN
    com.smartcart.order: INFO