server:
  port: ${INVENTORY_SERVICE_PORT:8084}


spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/inventory_db
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:8081/.well-known/jwks.json

  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: inventory-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.smartcart.common.event"
        spring.json.use.type.headers: false

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:${EUREKA_PORT:8761}/eureka/
    fetch-registry: true
    register-with-eureka: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:inventory-service} # optional for local dev
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}:${spring.profiles.active}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus              # expose all actuator endpoints for monitoring

  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: when-authorized  # only admins see full health info

  metrics:
    export:
      prometheus:
        enabled: true                # allow Prometheus scraping
    enable:
      all: true                      # enable all default metrics

  tracing:
    sampling:
      probability: 0.1                # trace 10% of requests to reduce overhead

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logging:
  level:
    root: WARN                 # production logs
    org.springframework: WARN
    com.smartcart: INFO         # your app packages

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

swagger:
  server-url: https://api.smartcart.com
