ALTER TABLE orders ADD COLUMN IF NOT EXISTS correlation_id VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS trace_id VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS last_span_id VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS last_event_id VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS last_event_type VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS last_event_source VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS workflow_updated_at TIMESTAMP;
